/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Annotated Top Level</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.AnnotatedTopLevel#getMetadata <em>Metadata</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.AnnotatedTopLevel#getMember <em>Member</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getAnnotatedTopLevel()
 * @model
 * @generated
 */
public interface AnnotatedTopLevel extends EObject
{
  /**
   * Returns the value of the '<em><b>Metadata</b></em>' containment reference list.
   * The list contents are of type {@link it.lorenzodeluca.dart.dart.Metadata}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metadata</em>' containment reference list.
   * @see it.lorenzodeluca.dart.dart.DartPackage#getAnnotatedTopLevel_Metadata()
   * @model containment="true"
   * @generated
   */
  EList<Metadata> getMetadata();

  /**
   * Returns the value of the '<em><b>Member</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Member</em>' containment reference.
   * @see #setMember(TopLevelDeclarationContent)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getAnnotatedTopLevel_Member()
   * @model containment="true"
   * @generated
   */
  TopLevelDeclarationContent getMember();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.AnnotatedTopLevel#getMember <em>Member</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Member</em>' containment reference.
   * @see #getMember()
   * @generated
   */
  void setMember(TopLevelDeclarationContent value);

} // AnnotatedTopLevel
