/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Argument List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.ArgumentList#getNamed <em>Named</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getArgumentList()
 * @model
 * @generated
 */
public interface ArgumentList extends EObject
{
  /**
   * Returns the value of the '<em><b>Named</b></em>' containment reference list.
   * The list contents are of type {@link it.lorenzodeluca.dart.dart.NamedArgument}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Named</em>' containment reference list.
   * @see it.lorenzodeluca.dart.dart.DartPackage#getArgumentList_Named()
   * @model containment="true"
   * @generated
   */
  EList<NamedArgument> getNamed();

} // ArgumentList
