/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collection Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getCollectionElement()
 * @model
 * @generated
 */
public interface CollectionElement extends EObject
{
} // CollectionElement
