/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constructor Designation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.ConstructorDesignation#getName <em>Name</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ConstructorDesignation#getTypeArguments <em>Type Arguments</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ConstructorDesignation#getConstructorId <em>Constructor Id</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getConstructorDesignation()
 * @model
 * @generated
 */
public interface ConstructorDesignation extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getConstructorDesignation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ConstructorDesignation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type Arguments</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Arguments</em>' containment reference.
   * @see #setTypeArguments(TypeArguments)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getConstructorDesignation_TypeArguments()
   * @model containment="true"
   * @generated
   */
  TypeArguments getTypeArguments();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ConstructorDesignation#getTypeArguments <em>Type Arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Arguments</em>' containment reference.
   * @see #getTypeArguments()
   * @generated
   */
  void setTypeArguments(TypeArguments value);

  /**
   * Returns the value of the '<em><b>Constructor Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constructor Id</em>' attribute.
   * @see #setConstructorId(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getConstructorDesignation_ConstructorId()
   * @model
   * @generated
   */
  String getConstructorId();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ConstructorDesignation#getConstructorId <em>Constructor Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constructor Id</em>' attribute.
   * @see #getConstructorId()
   * @generated
   */
  void setConstructorId(String value);

} // ConstructorDesignation
