/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.Declaration#isIsExternal <em>Is External</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.Declaration#isIsLate <em>Is Late</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.Declaration#isIsFinal <em>Is Final</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.Declaration#isIsConst <em>Is Const</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.Declaration#getType <em>Type</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.Declaration#getName <em>Name</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.Declaration#getInitialValue <em>Initial Value</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Is External</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is External</em>' attribute.
   * @see #setIsExternal(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getDeclaration_IsExternal()
   * @model
   * @generated
   */
  boolean isIsExternal();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.Declaration#isIsExternal <em>Is External</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is External</em>' attribute.
   * @see #isIsExternal()
   * @generated
   */
  void setIsExternal(boolean value);

  /**
   * Returns the value of the '<em><b>Is Late</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Late</em>' attribute.
   * @see #setIsLate(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getDeclaration_IsLate()
   * @model
   * @generated
   */
  boolean isIsLate();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.Declaration#isIsLate <em>Is Late</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Late</em>' attribute.
   * @see #isIsLate()
   * @generated
   */
  void setIsLate(boolean value);

  /**
   * Returns the value of the '<em><b>Is Final</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Final</em>' attribute.
   * @see #setIsFinal(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getDeclaration_IsFinal()
   * @model
   * @generated
   */
  boolean isIsFinal();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.Declaration#isIsFinal <em>Is Final</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Final</em>' attribute.
   * @see #isIsFinal()
   * @generated
   */
  void setIsFinal(boolean value);

  /**
   * Returns the value of the '<em><b>Is Const</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Const</em>' attribute.
   * @see #setIsConst(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getDeclaration_IsConst()
   * @model
   * @generated
   */
  boolean isIsConst();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.Declaration#isIsConst <em>Is Const</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Const</em>' attribute.
   * @see #isIsConst()
   * @generated
   */
  void setIsConst(boolean value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Type)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getDeclaration_Type()
   * @model containment="true"
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.Declaration#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.Declaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Initial Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial Value</em>' containment reference.
   * @see #setInitialValue(Expression)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getDeclaration_InitialValue()
   * @model containment="true"
   * @generated
   */
  Expression getInitialValue();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.Declaration#getInitialValue <em>Initial Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initial Value</em>' containment reference.
   * @see #getInitialValue()
   * @generated
   */
  void setInitialValue(Expression value);

} // Declaration
