/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Setter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.ExternalSetter#getMetadata <em>Metadata</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ExternalSetter#getSignature <em>Signature</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getExternalSetter()
 * @model
 * @generated
 */
public interface ExternalSetter extends TopLevelDeclaration
{
  /**
   * Returns the value of the '<em><b>Metadata</b></em>' containment reference list.
   * The list contents are of type {@link it.lorenzodeluca.dart.dart.Metadata}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metadata</em>' containment reference list.
   * @see it.lorenzodeluca.dart.dart.DartPackage#getExternalSetter_Metadata()
   * @model containment="true"
   * @generated
   */
  EList<Metadata> getMetadata();

  /**
   * Returns the value of the '<em><b>Signature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signature</em>' containment reference.
   * @see #setSignature(SetterSignature)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getExternalSetter_Signature()
   * @model containment="true"
   * @generated
   */
  SetterSignature getSignature();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ExternalSetter#getSignature <em>Signature</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signature</em>' containment reference.
   * @see #getSignature()
   * @generated
   */
  void setSignature(SetterSignature value);

} // ExternalSetter
