/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Initializer Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.ForInitializerStatement#getCond <em>Cond</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ForInitializerStatement#getUpdate <em>Update</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ForInitializerStatement#getLocalVar <em>Local Var</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ForInitializerStatement#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getForInitializerStatement()
 * @model
 * @generated
 */
public interface ForInitializerStatement extends ForLoopParts
{
  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(Expression)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getForInitializerStatement_Cond()
   * @model containment="true"
   * @generated
   */
  Expression getCond();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ForInitializerStatement#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(Expression value);

  /**
   * Returns the value of the '<em><b>Update</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Update</em>' containment reference.
   * @see #setUpdate(Expression)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getForInitializerStatement_Update()
   * @model containment="true"
   * @generated
   */
  Expression getUpdate();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ForInitializerStatement#getUpdate <em>Update</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Update</em>' containment reference.
   * @see #getUpdate()
   * @generated
   */
  void setUpdate(Expression value);

  /**
   * Returns the value of the '<em><b>Local Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local Var</em>' containment reference.
   * @see #setLocalVar(VariableDeclaration)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getForInitializerStatement_LocalVar()
   * @model containment="true"
   * @generated
   */
  VariableDeclaration getLocalVar();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ForInitializerStatement#getLocalVar <em>Local Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Local Var</em>' containment reference.
   * @see #getLocalVar()
   * @generated
   */
  void setLocalVar(VariableDeclaration value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getForInitializerStatement_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ForInitializerStatement#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

} // ForInitializerStatement
