/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formal Parameter Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.FormalParameterPart#getTypeParameters <em>Type Parameters</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.FormalParameterPart#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getFormalParameterPart()
 * @model
 * @generated
 */
public interface FormalParameterPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Parameters</em>' containment reference.
   * @see #setTypeParameters(TypeParameters)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getFormalParameterPart_TypeParameters()
   * @model containment="true"
   * @generated
   */
  TypeParameters getTypeParameters();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.FormalParameterPart#getTypeParameters <em>Type Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Parameters</em>' containment reference.
   * @see #getTypeParameters()
   * @generated
   */
  void setTypeParameters(TypeParameters value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference.
   * @see #setParameters(FormalParameterList)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getFormalParameterPart_Parameters()
   * @model containment="true"
   * @generated
   */
  FormalParameterList getParameters();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.FormalParameterPart#getParameters <em>Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameters</em>' containment reference.
   * @see #getParameters()
   * @generated
   */
  void setParameters(FormalParameterList value);

} // FormalParameterPart
