/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Type Tail</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.FunctionTypeTail#getTypeParameters <em>Type Parameters</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.FunctionTypeTail#getParameters <em>Parameters</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.FunctionTypeTail#isIsNullable <em>Is Nullable</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getFunctionTypeTail()
 * @model
 * @generated
 */
public interface FunctionTypeTail extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Parameters</em>' containment reference.
   * @see #setTypeParameters(TypeParameters)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getFunctionTypeTail_TypeParameters()
   * @model containment="true"
   * @generated
   */
  TypeParameters getTypeParameters();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.FunctionTypeTail#getTypeParameters <em>Type Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Parameters</em>' containment reference.
   * @see #getTypeParameters()
   * @generated
   */
  void setTypeParameters(TypeParameters value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference.
   * @see #setParameters(ParameterTypeList)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getFunctionTypeTail_Parameters()
   * @model containment="true"
   * @generated
   */
  ParameterTypeList getParameters();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.FunctionTypeTail#getParameters <em>Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameters</em>' containment reference.
   * @see #getParameters()
   * @generated
   */
  void setParameters(ParameterTypeList value);

  /**
   * Returns the value of the '<em><b>Is Nullable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Nullable</em>' attribute.
   * @see #setIsNullable(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getFunctionTypeTail_IsNullable()
   * @model
   * @generated
   */
  boolean isIsNullable();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.FunctionTypeTail#isIsNullable <em>Is Nullable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Nullable</em>' attribute.
   * @see #isIsNullable()
   * @generated
   */
  void setIsNullable(boolean value);

} // FunctionTypeTail
