/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Import Or Export Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#isIsImport <em>Is Import</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#getImportURI <em>Import URI</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#isIsDeferred <em>Is Deferred</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#getCombinators <em>Combinators</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#isIsExport <em>Is Export</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#getExportURI <em>Export URI</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getImportOrExportContent()
 * @model
 * @generated
 */
public interface ImportOrExportContent extends EObject
{
  /**
   * Returns the value of the '<em><b>Is Import</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Import</em>' attribute.
   * @see #setIsImport(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getImportOrExportContent_IsImport()
   * @model
   * @generated
   */
  boolean isIsImport();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#isIsImport <em>Is Import</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Import</em>' attribute.
   * @see #isIsImport()
   * @generated
   */
  void setIsImport(boolean value);

  /**
   * Returns the value of the '<em><b>Import URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import URI</em>' attribute.
   * @see #setImportURI(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getImportOrExportContent_ImportURI()
   * @model
   * @generated
   */
  String getImportURI();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#getImportURI <em>Import URI</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Import URI</em>' attribute.
   * @see #getImportURI()
   * @generated
   */
  void setImportURI(String value);

  /**
   * Returns the value of the '<em><b>Is Deferred</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Deferred</em>' attribute.
   * @see #setIsDeferred(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getImportOrExportContent_IsDeferred()
   * @model
   * @generated
   */
  boolean isIsDeferred();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#isIsDeferred <em>Is Deferred</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Deferred</em>' attribute.
   * @see #isIsDeferred()
   * @generated
   */
  void setIsDeferred(boolean value);

  /**
   * Returns the value of the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix</em>' attribute.
   * @see #setPrefix(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getImportOrExportContent_Prefix()
   * @model
   * @generated
   */
  String getPrefix();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#getPrefix <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix</em>' attribute.
   * @see #getPrefix()
   * @generated
   */
  void setPrefix(String value);

  /**
   * Returns the value of the '<em><b>Combinators</b></em>' containment reference list.
   * The list contents are of type {@link it.lorenzodeluca.dart.dart.Combinator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Combinators</em>' containment reference list.
   * @see it.lorenzodeluca.dart.dart.DartPackage#getImportOrExportContent_Combinators()
   * @model containment="true"
   * @generated
   */
  EList<Combinator> getCombinators();

  /**
   * Returns the value of the '<em><b>Is Export</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Export</em>' attribute.
   * @see #setIsExport(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getImportOrExportContent_IsExport()
   * @model
   * @generated
   */
  boolean isIsExport();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#isIsExport <em>Is Export</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Export</em>' attribute.
   * @see #isIsExport()
   * @generated
   */
  void setIsExport(boolean value);

  /**
   * Returns the value of the '<em><b>Export URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Export URI</em>' attribute.
   * @see #setExportURI(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getImportOrExportContent_ExportURI()
   * @model
   * @generated
   */
  String getExportURI();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ImportOrExportContent#getExportURI <em>Export URI</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Export URI</em>' attribute.
   * @see #getExportURI()
   * @generated
   */
  void setExportURI(String value);

} // ImportOrExportContent
