/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Library Export</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.LibraryExport#getExportURI <em>Export URI</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getLibraryExport()
 * @model
 * @generated
 */
public interface LibraryExport extends ImportOrExport
{
  /**
   * Returns the value of the '<em><b>Export URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Export URI</em>' attribute.
   * @see #setExportURI(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getLibraryExport_ExportURI()
   * @model
   * @generated
   */
  String getExportURI();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.LibraryExport#getExportURI <em>Export URI</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Export URI</em>' attribute.
   * @see #getExportURI()
   * @generated
   */
  void setExportURI(String value);

} // LibraryExport
