/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.ListLiteral#isIsConst <em>Is Const</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ListLiteral#getTypeArguments <em>Type Arguments</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.ListLiteral#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getListLiteral()
 * @model
 * @generated
 */
public interface ListLiteral extends Expression
{
  /**
   * Returns the value of the '<em><b>Is Const</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Const</em>' attribute.
   * @see #setIsConst(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getListLiteral_IsConst()
   * @model
   * @generated
   */
  boolean isIsConst();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ListLiteral#isIsConst <em>Is Const</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Const</em>' attribute.
   * @see #isIsConst()
   * @generated
   */
  void setIsConst(boolean value);

  /**
   * Returns the value of the '<em><b>Type Arguments</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Arguments</em>' containment reference.
   * @see #setTypeArguments(TypeArguments)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getListLiteral_TypeArguments()
   * @model containment="true"
   * @generated
   */
  TypeArguments getTypeArguments();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.ListLiteral#getTypeArguments <em>Type Arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Arguments</em>' containment reference.
   * @see #getTypeArguments()
   * @generated
   */
  void setTypeArguments(TypeArguments value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link it.lorenzodeluca.dart.dart.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see it.lorenzodeluca.dart.dart.DartPackage#getListLiteral_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getElements();

} // ListLiteral
