/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.MapElement#getKey <em>Key</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.MapElement#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getMapElement()
 * @model
 * @generated
 */
public interface MapElement extends CollectionElement
{
  /**
   * Returns the value of the '<em><b>Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' containment reference.
   * @see #setKey(Expression)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getMapElement_Key()
   * @model containment="true"
   * @generated
   */
  Expression getKey();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.MapElement#getKey <em>Key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' containment reference.
   * @see #getKey()
   * @generated
   */
  void setKey(Expression value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Expression)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getMapElement_Value()
   * @model containment="true"
   * @generated
   */
  Expression getValue();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.MapElement#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Expression value);

} // MapElement
