/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Invocation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.MethodInvocation#getReceiver <em>Receiver</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.MethodInvocation#getMethod <em>Method</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.MethodInvocation#getTypeArguments <em>Type Arguments</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.MethodInvocation#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getMethodInvocation()
 * @model
 * @generated
 */
public interface MethodInvocation extends Expression
{
  /**
   * Returns the value of the '<em><b>Receiver</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Receiver</em>' containment reference.
   * @see #setReceiver(Expression)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getMethodInvocation_Receiver()
   * @model containment="true"
   * @generated
   */
  Expression getReceiver();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.MethodInvocation#getReceiver <em>Receiver</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Receiver</em>' containment reference.
   * @see #getReceiver()
   * @generated
   */
  void setReceiver(Expression value);

  /**
   * Returns the value of the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method</em>' attribute.
   * @see #setMethod(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getMethodInvocation_Method()
   * @model
   * @generated
   */
  String getMethod();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.MethodInvocation#getMethod <em>Method</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method</em>' attribute.
   * @see #getMethod()
   * @generated
   */
  void setMethod(String value);

  /**
   * Returns the value of the '<em><b>Type Arguments</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Arguments</em>' containment reference.
   * @see #setTypeArguments(TypeArguments)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getMethodInvocation_TypeArguments()
   * @model containment="true"
   * @generated
   */
  TypeArguments getTypeArguments();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.MethodInvocation#getTypeArguments <em>Type Arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Arguments</em>' containment reference.
   * @see #getTypeArguments()
   * @generated
   */
  void setTypeArguments(TypeArguments value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference.
   * @see #setArgs(Arguments)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getMethodInvocation_Args()
   * @model containment="true"
   * @generated
   */
  Arguments getArgs();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.MethodInvocation#getArgs <em>Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' containment reference.
   * @see #getArgs()
   * @generated
   */
  void setArgs(Arguments value);

} // MethodInvocation
