/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mixin Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.MixinDeclaration#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getMixinDeclaration()
 * @model
 * @generated
 */
public interface MixinDeclaration extends TopLevelDeclaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getMixinDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.MixinDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // MixinDeclaration
