/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>New Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.NewExpression#getType <em>Type</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.NewExpression#getConstructor <em>Constructor</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.NewExpression#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getNewExpression()
 * @model
 * @generated
 */
public interface NewExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Type)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getNewExpression_Type()
   * @model containment="true"
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.NewExpression#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Constructor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constructor</em>' attribute.
   * @see #setConstructor(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getNewExpression_Constructor()
   * @model
   * @generated
   */
  String getConstructor();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.NewExpression#getConstructor <em>Constructor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constructor</em>' attribute.
   * @see #getConstructor()
   * @generated
   */
  void setConstructor(String value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference.
   * @see #setArgs(Arguments)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getNewExpression_Args()
   * @model containment="true"
   * @generated
   */
  Arguments getArgs();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.NewExpression#getArgs <em>Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' containment reference.
   * @see #getArgs()
   * @generated
   */
  void setArgs(Arguments value);

} // NewExpression
