/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Normal Formal Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.NormalFormalParameter#getMetadata <em>Metadata</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.NormalFormalParameter#isIsCovariant <em>Is Covariant</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.NormalFormalParameter#getType <em>Type</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.NormalFormalParameter#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getNormalFormalParameter()
 * @model
 * @generated
 */
public interface NormalFormalParameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Metadata</b></em>' containment reference list.
   * The list contents are of type {@link it.lorenzodeluca.dart.dart.Metadata}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metadata</em>' containment reference list.
   * @see it.lorenzodeluca.dart.dart.DartPackage#getNormalFormalParameter_Metadata()
   * @model containment="true"
   * @generated
   */
  EList<Metadata> getMetadata();

  /**
   * Returns the value of the '<em><b>Is Covariant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Covariant</em>' attribute.
   * @see #setIsCovariant(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getNormalFormalParameter_IsCovariant()
   * @model
   * @generated
   */
  boolean isIsCovariant();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.NormalFormalParameter#isIsCovariant <em>Is Covariant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Covariant</em>' attribute.
   * @see #isIsCovariant()
   * @generated
   */
  void setIsCovariant(boolean value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Type)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getNormalFormalParameter_Type()
   * @model containment="true"
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.NormalFormalParameter#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getNormalFormalParameter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.NormalFormalParameter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // NormalFormalParameter
