/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Switch Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.SwitchStatement#getExpression <em>Expression</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.SwitchStatement#getCases <em>Cases</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.SwitchStatement#getDefaultCase <em>Default Case</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getSwitchStatement()
 * @model
 * @generated
 */
public interface SwitchStatement extends NonLabelledStatement
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getSwitchStatement_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.SwitchStatement#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Cases</b></em>' containment reference list.
   * The list contents are of type {@link it.lorenzodeluca.dart.dart.SwitchCase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cases</em>' containment reference list.
   * @see it.lorenzodeluca.dart.dart.DartPackage#getSwitchStatement_Cases()
   * @model containment="true"
   * @generated
   */
  EList<SwitchCase> getCases();

  /**
   * Returns the value of the '<em><b>Default Case</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Case</em>' containment reference.
   * @see #setDefaultCase(DefaultCase)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getSwitchStatement_DefaultCase()
   * @model containment="true"
   * @generated
   */
  DefaultCase getDefaultCase();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.SwitchStatement#getDefaultCase <em>Default Case</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Case</em>' containment reference.
   * @see #getDefaultCase()
   * @generated
   */
  void setDefaultCase(DefaultCase value);

} // SwitchStatement
