/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Alias</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.TypeAlias#getMetadata <em>Metadata</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.TypeAlias#getName <em>Name</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.TypeAlias#getTypeParameters <em>Type Parameters</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.TypeAlias#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getTypeAlias()
 * @model
 * @generated
 */
public interface TypeAlias extends TopLevelDeclaration
{
  /**
   * Returns the value of the '<em><b>Metadata</b></em>' containment reference list.
   * The list contents are of type {@link it.lorenzodeluca.dart.dart.Metadata}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metadata</em>' containment reference list.
   * @see it.lorenzodeluca.dart.dart.DartPackage#getTypeAlias_Metadata()
   * @model containment="true"
   * @generated
   */
  EList<Metadata> getMetadata();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getTypeAlias_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.TypeAlias#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Parameters</em>' containment reference.
   * @see #setTypeParameters(TypeParameters)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getTypeAlias_TypeParameters()
   * @model containment="true"
   * @generated
   */
  TypeParameters getTypeParameters();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.TypeAlias#getTypeParameters <em>Type Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Parameters</em>' containment reference.
   * @see #getTypeParameters()
   * @generated
   */
  void setTypeParameters(TypeParameters value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Type)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getTypeAlias_Type()
   * @model containment="true"
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.TypeAlias#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

} // TypeAlias
