/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Not Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.TypeNotFunction#isIsVoid <em>Is Void</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.TypeNotFunction#isIsNullable <em>Is Nullable</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.TypeNotFunction#getName <em>Name</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.TypeNotFunction#getTypeArguments <em>Type Arguments</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getTypeNotFunction()
 * @model
 * @generated
 */
public interface TypeNotFunction extends Type
{
  /**
   * Returns the value of the '<em><b>Is Void</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Void</em>' attribute.
   * @see #setIsVoid(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getTypeNotFunction_IsVoid()
   * @model
   * @generated
   */
  boolean isIsVoid();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.TypeNotFunction#isIsVoid <em>Is Void</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Void</em>' attribute.
   * @see #isIsVoid()
   * @generated
   */
  void setIsVoid(boolean value);

  /**
   * Returns the value of the '<em><b>Is Nullable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Nullable</em>' attribute.
   * @see #setIsNullable(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getTypeNotFunction_IsNullable()
   * @model
   * @generated
   */
  boolean isIsNullable();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.TypeNotFunction#isIsNullable <em>Is Nullable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Nullable</em>' attribute.
   * @see #isIsNullable()
   * @generated
   */
  void setIsNullable(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(TypeName)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getTypeNotFunction_Name()
   * @model containment="true"
   * @generated
   */
  TypeName getName();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.TypeNotFunction#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(TypeName value);

  /**
   * Returns the value of the '<em><b>Type Arguments</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Arguments</em>' containment reference.
   * @see #setTypeArguments(TypeArguments)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getTypeNotFunction_TypeArguments()
   * @model containment="true"
   * @generated
   */
  TypeArguments getTypeArguments();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.TypeNotFunction#getTypeArguments <em>Type Arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Arguments</em>' containment reference.
   * @see #getTypeArguments()
   * @generated
   */
  void setTypeArguments(TypeArguments value);

} // TypeNotFunction
