/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.VariableDeclaration#isLate <em>Late</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.VariableDeclaration#getModifier <em>Modifier</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.VariableDeclaration#getType <em>Type</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.VariableDeclaration#getVariables <em>Variables</em>}</li>
 * </ul>
 *
 * @see it.lorenzodeluca.dart.dart.DartPackage#getVariableDeclaration()
 * @model
 * @generated
 */
public interface VariableDeclaration extends TopLevelDeclaration
{
  /**
   * Returns the value of the '<em><b>Late</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Late</em>' attribute.
   * @see #setLate(boolean)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getVariableDeclaration_Late()
   * @model
   * @generated
   */
  boolean isLate();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.VariableDeclaration#isLate <em>Late</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Late</em>' attribute.
   * @see #isLate()
   * @generated
   */
  void setLate(boolean value);

  /**
   * Returns the value of the '<em><b>Modifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modifier</em>' attribute.
   * @see #setModifier(String)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getVariableDeclaration_Modifier()
   * @model
   * @generated
   */
  String getModifier();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.VariableDeclaration#getModifier <em>Modifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Modifier</em>' attribute.
   * @see #getModifier()
   * @generated
   */
  void setModifier(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Type)
   * @see it.lorenzodeluca.dart.dart.DartPackage#getVariableDeclaration_Type()
   * @model containment="true"
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link it.lorenzodeluca.dart.dart.VariableDeclaration#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link it.lorenzodeluca.dart.dart.VariableSingleDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see it.lorenzodeluca.dart.dart.DartPackage#getVariableDeclaration_Variables()
   * @model containment="true"
   * @generated
   */
  EList<VariableSingleDeclaration> getVariables();

} // VariableDeclaration
