/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart.impl;

import it.lorenzodeluca.dart.dart.Block;
import it.lorenzodeluca.dart.dart.CatchClause;
import it.lorenzodeluca.dart.dart.DartPackage;
import it.lorenzodeluca.dart.dart.Type;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Catch Clause</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.CatchClauseImpl#getType <em>Type</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.CatchClauseImpl#getException <em>Exception</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.CatchClauseImpl#getStackTrace <em>Stack Trace</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.CatchClauseImpl#getBlock <em>Block</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CatchClauseImpl extends MinimalEObjectImpl.Container implements CatchClause
{
  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected Type type;

  /**
   * The default value of the '{@link #getException() <em>Exception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getException()
   * @generated
   * @ordered
   */
  protected static final String EXCEPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getException() <em>Exception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getException()
   * @generated
   * @ordered
   */
  protected String exception = EXCEPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getStackTrace() <em>Stack Trace</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStackTrace()
   * @generated
   * @ordered
   */
  protected static final String STACK_TRACE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStackTrace() <em>Stack Trace</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStackTrace()
   * @generated
   * @ordered
   */
  protected String stackTrace = STACK_TRACE_EDEFAULT;

  /**
   * The cached value of the '{@link #getBlock() <em>Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBlock()
   * @generated
   * @ordered
   */
  protected Block block;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CatchClauseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DartPackage.Literals.CATCH_CLAUSE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Type getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(Type newType, NotificationChain msgs)
  {
    Type oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DartPackage.CATCH_CLAUSE__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(Type newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DartPackage.CATCH_CLAUSE__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DartPackage.CATCH_CLAUSE__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.CATCH_CLAUSE__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getException()
  {
    return exception;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setException(String newException)
  {
    String oldException = exception;
    exception = newException;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.CATCH_CLAUSE__EXCEPTION, oldException, exception));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStackTrace()
  {
    return stackTrace;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStackTrace(String newStackTrace)
  {
    String oldStackTrace = stackTrace;
    stackTrace = newStackTrace;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.CATCH_CLAUSE__STACK_TRACE, oldStackTrace, stackTrace));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Block getBlock()
  {
    return block;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBlock(Block newBlock, NotificationChain msgs)
  {
    Block oldBlock = block;
    block = newBlock;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DartPackage.CATCH_CLAUSE__BLOCK, oldBlock, newBlock);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBlock(Block newBlock)
  {
    if (newBlock != block)
    {
      NotificationChain msgs = null;
      if (block != null)
        msgs = ((InternalEObject)block).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DartPackage.CATCH_CLAUSE__BLOCK, null, msgs);
      if (newBlock != null)
        msgs = ((InternalEObject)newBlock).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DartPackage.CATCH_CLAUSE__BLOCK, null, msgs);
      msgs = basicSetBlock(newBlock, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.CATCH_CLAUSE__BLOCK, newBlock, newBlock));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DartPackage.CATCH_CLAUSE__TYPE:
        return basicSetType(null, msgs);
      case DartPackage.CATCH_CLAUSE__BLOCK:
        return basicSetBlock(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DartPackage.CATCH_CLAUSE__TYPE:
        return getType();
      case DartPackage.CATCH_CLAUSE__EXCEPTION:
        return getException();
      case DartPackage.CATCH_CLAUSE__STACK_TRACE:
        return getStackTrace();
      case DartPackage.CATCH_CLAUSE__BLOCK:
        return getBlock();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DartPackage.CATCH_CLAUSE__TYPE:
        setType((Type)newValue);
        return;
      case DartPackage.CATCH_CLAUSE__EXCEPTION:
        setException((String)newValue);
        return;
      case DartPackage.CATCH_CLAUSE__STACK_TRACE:
        setStackTrace((String)newValue);
        return;
      case DartPackage.CATCH_CLAUSE__BLOCK:
        setBlock((Block)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.CATCH_CLAUSE__TYPE:
        setType((Type)null);
        return;
      case DartPackage.CATCH_CLAUSE__EXCEPTION:
        setException(EXCEPTION_EDEFAULT);
        return;
      case DartPackage.CATCH_CLAUSE__STACK_TRACE:
        setStackTrace(STACK_TRACE_EDEFAULT);
        return;
      case DartPackage.CATCH_CLAUSE__BLOCK:
        setBlock((Block)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.CATCH_CLAUSE__TYPE:
        return type != null;
      case DartPackage.CATCH_CLAUSE__EXCEPTION:
        return EXCEPTION_EDEFAULT == null ? exception != null : !EXCEPTION_EDEFAULT.equals(exception);
      case DartPackage.CATCH_CLAUSE__STACK_TRACE:
        return STACK_TRACE_EDEFAULT == null ? stackTrace != null : !STACK_TRACE_EDEFAULT.equals(stackTrace);
      case DartPackage.CATCH_CLAUSE__BLOCK:
        return block != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (exception: ");
    result.append(exception);
    result.append(", stackTrace: ");
    result.append(stackTrace);
    result.append(')');
    return result.toString();
  }

} //CatchClauseImpl
