/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart.impl;

import it.lorenzodeluca.dart.dart.ConstructorName;
import it.lorenzodeluca.dart.dart.DartPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Constructor Name</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.ConstructorNameImpl#getClassName <em>Class Name</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.ConstructorNameImpl#getConstructorId <em>Constructor Id</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConstructorNameImpl extends MinimalEObjectImpl.Container implements ConstructorName
{
  /**
   * The default value of the '{@link #getClassName() <em>Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClassName()
   * @generated
   * @ordered
   */
  protected static final String CLASS_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getClassName() <em>Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClassName()
   * @generated
   * @ordered
   */
  protected String className = CLASS_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getConstructorId() <em>Constructor Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstructorId()
   * @generated
   * @ordered
   */
  protected static final String CONSTRUCTOR_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getConstructorId() <em>Constructor Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstructorId()
   * @generated
   * @ordered
   */
  protected String constructorId = CONSTRUCTOR_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstructorNameImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DartPackage.Literals.CONSTRUCTOR_NAME;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getClassName()
  {
    return className;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setClassName(String newClassName)
  {
    String oldClassName = className;
    className = newClassName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.CONSTRUCTOR_NAME__CLASS_NAME, oldClassName, className));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getConstructorId()
  {
    return constructorId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConstructorId(String newConstructorId)
  {
    String oldConstructorId = constructorId;
    constructorId = newConstructorId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.CONSTRUCTOR_NAME__CONSTRUCTOR_ID, oldConstructorId, constructorId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DartPackage.CONSTRUCTOR_NAME__CLASS_NAME:
        return getClassName();
      case DartPackage.CONSTRUCTOR_NAME__CONSTRUCTOR_ID:
        return getConstructorId();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DartPackage.CONSTRUCTOR_NAME__CLASS_NAME:
        setClassName((String)newValue);
        return;
      case DartPackage.CONSTRUCTOR_NAME__CONSTRUCTOR_ID:
        setConstructorId((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.CONSTRUCTOR_NAME__CLASS_NAME:
        setClassName(CLASS_NAME_EDEFAULT);
        return;
      case DartPackage.CONSTRUCTOR_NAME__CONSTRUCTOR_ID:
        setConstructorId(CONSTRUCTOR_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.CONSTRUCTOR_NAME__CLASS_NAME:
        return CLASS_NAME_EDEFAULT == null ? className != null : !CLASS_NAME_EDEFAULT.equals(className);
      case DartPackage.CONSTRUCTOR_NAME__CONSTRUCTOR_ID:
        return CONSTRUCTOR_ID_EDEFAULT == null ? constructorId != null : !CONSTRUCTOR_ID_EDEFAULT.equals(constructorId);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (className: ");
    result.append(className);
    result.append(", constructorId: ");
    result.append(constructorId);
    result.append(')');
    return result.toString();
  }

} //ConstructorNameImpl
