/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart.impl;

import it.lorenzodeluca.dart.dart.ConstructorDesignation;
import it.lorenzodeluca.dart.dart.DartPackage;
import it.lorenzodeluca.dart.dart.TypeArguments;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Constructor Designation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.ConstructorDesignationImpl#getName <em>Name</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.ConstructorDesignationImpl#getTypeArguments <em>Type Arguments</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.ConstructorDesignationImpl#getConstructorId <em>Constructor Id</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConstructorDesignationImpl extends MinimalEObjectImpl.Container implements ConstructorDesignation
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTypeArguments() <em>Type Arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeArguments()
   * @generated
   * @ordered
   */
  protected TypeArguments typeArguments;

  /**
   * The default value of the '{@link #getConstructorId() <em>Constructor Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstructorId()
   * @generated
   * @ordered
   */
  protected static final String CONSTRUCTOR_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getConstructorId() <em>Constructor Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstructorId()
   * @generated
   * @ordered
   */
  protected String constructorId = CONSTRUCTOR_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstructorDesignationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DartPackage.Literals.CONSTRUCTOR_DESIGNATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.CONSTRUCTOR_DESIGNATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypeArguments getTypeArguments()
  {
    return typeArguments;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeArguments(TypeArguments newTypeArguments, NotificationChain msgs)
  {
    TypeArguments oldTypeArguments = typeArguments;
    typeArguments = newTypeArguments;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DartPackage.CONSTRUCTOR_DESIGNATION__TYPE_ARGUMENTS, oldTypeArguments, newTypeArguments);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTypeArguments(TypeArguments newTypeArguments)
  {
    if (newTypeArguments != typeArguments)
    {
      NotificationChain msgs = null;
      if (typeArguments != null)
        msgs = ((InternalEObject)typeArguments).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DartPackage.CONSTRUCTOR_DESIGNATION__TYPE_ARGUMENTS, null, msgs);
      if (newTypeArguments != null)
        msgs = ((InternalEObject)newTypeArguments).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DartPackage.CONSTRUCTOR_DESIGNATION__TYPE_ARGUMENTS, null, msgs);
      msgs = basicSetTypeArguments(newTypeArguments, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.CONSTRUCTOR_DESIGNATION__TYPE_ARGUMENTS, newTypeArguments, newTypeArguments));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getConstructorId()
  {
    return constructorId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConstructorId(String newConstructorId)
  {
    String oldConstructorId = constructorId;
    constructorId = newConstructorId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.CONSTRUCTOR_DESIGNATION__CONSTRUCTOR_ID, oldConstructorId, constructorId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DartPackage.CONSTRUCTOR_DESIGNATION__TYPE_ARGUMENTS:
        return basicSetTypeArguments(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DartPackage.CONSTRUCTOR_DESIGNATION__NAME:
        return getName();
      case DartPackage.CONSTRUCTOR_DESIGNATION__TYPE_ARGUMENTS:
        return getTypeArguments();
      case DartPackage.CONSTRUCTOR_DESIGNATION__CONSTRUCTOR_ID:
        return getConstructorId();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DartPackage.CONSTRUCTOR_DESIGNATION__NAME:
        setName((String)newValue);
        return;
      case DartPackage.CONSTRUCTOR_DESIGNATION__TYPE_ARGUMENTS:
        setTypeArguments((TypeArguments)newValue);
        return;
      case DartPackage.CONSTRUCTOR_DESIGNATION__CONSTRUCTOR_ID:
        setConstructorId((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.CONSTRUCTOR_DESIGNATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DartPackage.CONSTRUCTOR_DESIGNATION__TYPE_ARGUMENTS:
        setTypeArguments((TypeArguments)null);
        return;
      case DartPackage.CONSTRUCTOR_DESIGNATION__CONSTRUCTOR_ID:
        setConstructorId(CONSTRUCTOR_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.CONSTRUCTOR_DESIGNATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DartPackage.CONSTRUCTOR_DESIGNATION__TYPE_ARGUMENTS:
        return typeArguments != null;
      case DartPackage.CONSTRUCTOR_DESIGNATION__CONSTRUCTOR_ID:
        return CONSTRUCTOR_ID_EDEFAULT == null ? constructorId != null : !CONSTRUCTOR_ID_EDEFAULT.equals(constructorId);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", constructorId: ");
    result.append(constructorId);
    result.append(')');
    return result.toString();
  }

} //ConstructorDesignationImpl
