/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart.impl;

import it.lorenzodeluca.dart.dart.DartPackage;
import it.lorenzodeluca.dart.dart.Expression;
import it.lorenzodeluca.dart.dart.ForInitializerStatement;
import it.lorenzodeluca.dart.dart.VariableDeclaration;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>For Initializer Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.ForInitializerStatementImpl#getCond <em>Cond</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.ForInitializerStatementImpl#getUpdate <em>Update</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.ForInitializerStatementImpl#getLocalVar <em>Local Var</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.ForInitializerStatementImpl#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ForInitializerStatementImpl extends ForLoopPartsImpl implements ForInitializerStatement
{
  /**
   * The cached value of the '{@link #getCond() <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCond()
   * @generated
   * @ordered
   */
  protected Expression cond;

  /**
   * The cached value of the '{@link #getUpdate() <em>Update</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUpdate()
   * @generated
   * @ordered
   */
  protected Expression update;

  /**
   * The cached value of the '{@link #getLocalVar() <em>Local Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocalVar()
   * @generated
   * @ordered
   */
  protected VariableDeclaration localVar;

  /**
   * The cached value of the '{@link #getExpr() <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpr()
   * @generated
   * @ordered
   */
  protected Expression expr;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ForInitializerStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DartPackage.eINSTANCE.getForInitializerStatement();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getCond()
  {
    return cond;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCond(Expression newCond, NotificationChain msgs)
  {
    Expression oldCond = cond;
    cond = newCond;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DartPackage.FOR_INITIALIZER_STATEMENT__COND, oldCond, newCond);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCond(Expression newCond)
  {
    if (newCond != cond)
    {
      NotificationChain msgs = null;
      if (cond != null)
        msgs = ((InternalEObject)cond).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DartPackage.FOR_INITIALIZER_STATEMENT__COND, null, msgs);
      if (newCond != null)
        msgs = ((InternalEObject)newCond).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DartPackage.FOR_INITIALIZER_STATEMENT__COND, null, msgs);
      msgs = basicSetCond(newCond, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.FOR_INITIALIZER_STATEMENT__COND, newCond, newCond));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getUpdate()
  {
    return update;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUpdate(Expression newUpdate, NotificationChain msgs)
  {
    Expression oldUpdate = update;
    update = newUpdate;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DartPackage.FOR_INITIALIZER_STATEMENT__UPDATE, oldUpdate, newUpdate);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUpdate(Expression newUpdate)
  {
    if (newUpdate != update)
    {
      NotificationChain msgs = null;
      if (update != null)
        msgs = ((InternalEObject)update).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DartPackage.FOR_INITIALIZER_STATEMENT__UPDATE, null, msgs);
      if (newUpdate != null)
        msgs = ((InternalEObject)newUpdate).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DartPackage.FOR_INITIALIZER_STATEMENT__UPDATE, null, msgs);
      msgs = basicSetUpdate(newUpdate, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.FOR_INITIALIZER_STATEMENT__UPDATE, newUpdate, newUpdate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableDeclaration getLocalVar()
  {
    return localVar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLocalVar(VariableDeclaration newLocalVar, NotificationChain msgs)
  {
    VariableDeclaration oldLocalVar = localVar;
    localVar = newLocalVar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DartPackage.FOR_INITIALIZER_STATEMENT__LOCAL_VAR, oldLocalVar, newLocalVar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocalVar(VariableDeclaration newLocalVar)
  {
    if (newLocalVar != localVar)
    {
      NotificationChain msgs = null;
      if (localVar != null)
        msgs = ((InternalEObject)localVar).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DartPackage.FOR_INITIALIZER_STATEMENT__LOCAL_VAR, null, msgs);
      if (newLocalVar != null)
        msgs = ((InternalEObject)newLocalVar).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DartPackage.FOR_INITIALIZER_STATEMENT__LOCAL_VAR, null, msgs);
      msgs = basicSetLocalVar(newLocalVar, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.FOR_INITIALIZER_STATEMENT__LOCAL_VAR, newLocalVar, newLocalVar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getExpr()
  {
    return expr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpr(Expression newExpr, NotificationChain msgs)
  {
    Expression oldExpr = expr;
    expr = newExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DartPackage.FOR_INITIALIZER_STATEMENT__EXPR, oldExpr, newExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExpr(Expression newExpr)
  {
    if (newExpr != expr)
    {
      NotificationChain msgs = null;
      if (expr != null)
        msgs = ((InternalEObject)expr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DartPackage.FOR_INITIALIZER_STATEMENT__EXPR, null, msgs);
      if (newExpr != null)
        msgs = ((InternalEObject)newExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DartPackage.FOR_INITIALIZER_STATEMENT__EXPR, null, msgs);
      msgs = basicSetExpr(newExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.FOR_INITIALIZER_STATEMENT__EXPR, newExpr, newExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DartPackage.FOR_INITIALIZER_STATEMENT__COND:
        return basicSetCond(null, msgs);
      case DartPackage.FOR_INITIALIZER_STATEMENT__UPDATE:
        return basicSetUpdate(null, msgs);
      case DartPackage.FOR_INITIALIZER_STATEMENT__LOCAL_VAR:
        return basicSetLocalVar(null, msgs);
      case DartPackage.FOR_INITIALIZER_STATEMENT__EXPR:
        return basicSetExpr(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DartPackage.FOR_INITIALIZER_STATEMENT__COND:
        return getCond();
      case DartPackage.FOR_INITIALIZER_STATEMENT__UPDATE:
        return getUpdate();
      case DartPackage.FOR_INITIALIZER_STATEMENT__LOCAL_VAR:
        return getLocalVar();
      case DartPackage.FOR_INITIALIZER_STATEMENT__EXPR:
        return getExpr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DartPackage.FOR_INITIALIZER_STATEMENT__COND:
        setCond((Expression)newValue);
        return;
      case DartPackage.FOR_INITIALIZER_STATEMENT__UPDATE:
        setUpdate((Expression)newValue);
        return;
      case DartPackage.FOR_INITIALIZER_STATEMENT__LOCAL_VAR:
        setLocalVar((VariableDeclaration)newValue);
        return;
      case DartPackage.FOR_INITIALIZER_STATEMENT__EXPR:
        setExpr((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.FOR_INITIALIZER_STATEMENT__COND:
        setCond((Expression)null);
        return;
      case DartPackage.FOR_INITIALIZER_STATEMENT__UPDATE:
        setUpdate((Expression)null);
        return;
      case DartPackage.FOR_INITIALIZER_STATEMENT__LOCAL_VAR:
        setLocalVar((VariableDeclaration)null);
        return;
      case DartPackage.FOR_INITIALIZER_STATEMENT__EXPR:
        setExpr((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.FOR_INITIALIZER_STATEMENT__COND:
        return cond != null;
      case DartPackage.FOR_INITIALIZER_STATEMENT__UPDATE:
        return update != null;
      case DartPackage.FOR_INITIALIZER_STATEMENT__LOCAL_VAR:
        return localVar != null;
      case DartPackage.FOR_INITIALIZER_STATEMENT__EXPR:
        return expr != null;
    }
    return super.eIsSet(featureID);
  }

} //ForInitializerStatementImpl
