/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart.impl;

import it.lorenzodeluca.dart.dart.DartPackage;
import it.lorenzodeluca.dart.dart.Metadata;
import it.lorenzodeluca.dart.dart.NamedParameterType;
import it.lorenzodeluca.dart.dart.Type;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Named Parameter Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.NamedParameterTypeImpl#getMetadata <em>Metadata</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.NamedParameterTypeImpl#isIsRequired <em>Is Required</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.NamedParameterTypeImpl#getType <em>Type</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.NamedParameterTypeImpl#getName <em>Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NamedParameterTypeImpl extends MinimalEObjectImpl.Container implements NamedParameterType
{
  /**
   * The cached value of the '{@link #getMetadata() <em>Metadata</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetadata()
   * @generated
   * @ordered
   */
  protected EList<Metadata> metadata;

  /**
   * The default value of the '{@link #isIsRequired() <em>Is Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsRequired()
   * @generated
   * @ordered
   */
  protected static final boolean IS_REQUIRED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsRequired() <em>Is Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsRequired()
   * @generated
   * @ordered
   */
  protected boolean isRequired = IS_REQUIRED_EDEFAULT;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected Type type;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NamedParameterTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DartPackage.eINSTANCE.getNamedParameterType();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Metadata> getMetadata()
  {
    if (metadata == null)
    {
      metadata = new EObjectContainmentEList<Metadata>(Metadata.class, this, DartPackage.NAMED_PARAMETER_TYPE__METADATA);
    }
    return metadata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsRequired()
  {
    return isRequired;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsRequired(boolean newIsRequired)
  {
    boolean oldIsRequired = isRequired;
    isRequired = newIsRequired;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.NAMED_PARAMETER_TYPE__IS_REQUIRED, oldIsRequired, isRequired));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Type getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(Type newType, NotificationChain msgs)
  {
    Type oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DartPackage.NAMED_PARAMETER_TYPE__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(Type newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DartPackage.NAMED_PARAMETER_TYPE__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DartPackage.NAMED_PARAMETER_TYPE__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.NAMED_PARAMETER_TYPE__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.NAMED_PARAMETER_TYPE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DartPackage.NAMED_PARAMETER_TYPE__METADATA:
        return ((InternalEList<?>)getMetadata()).basicRemove(otherEnd, msgs);
      case DartPackage.NAMED_PARAMETER_TYPE__TYPE:
        return basicSetType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DartPackage.NAMED_PARAMETER_TYPE__METADATA:
        return getMetadata();
      case DartPackage.NAMED_PARAMETER_TYPE__IS_REQUIRED:
        return isIsRequired();
      case DartPackage.NAMED_PARAMETER_TYPE__TYPE:
        return getType();
      case DartPackage.NAMED_PARAMETER_TYPE__NAME:
        return getName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DartPackage.NAMED_PARAMETER_TYPE__METADATA:
        getMetadata().clear();
        getMetadata().addAll((Collection<? extends Metadata>)newValue);
        return;
      case DartPackage.NAMED_PARAMETER_TYPE__IS_REQUIRED:
        setIsRequired((Boolean)newValue);
        return;
      case DartPackage.NAMED_PARAMETER_TYPE__TYPE:
        setType((Type)newValue);
        return;
      case DartPackage.NAMED_PARAMETER_TYPE__NAME:
        setName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.NAMED_PARAMETER_TYPE__METADATA:
        getMetadata().clear();
        return;
      case DartPackage.NAMED_PARAMETER_TYPE__IS_REQUIRED:
        setIsRequired(IS_REQUIRED_EDEFAULT);
        return;
      case DartPackage.NAMED_PARAMETER_TYPE__TYPE:
        setType((Type)null);
        return;
      case DartPackage.NAMED_PARAMETER_TYPE__NAME:
        setName(NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.NAMED_PARAMETER_TYPE__METADATA:
        return metadata != null && !metadata.isEmpty();
      case DartPackage.NAMED_PARAMETER_TYPE__IS_REQUIRED:
        return isRequired != IS_REQUIRED_EDEFAULT;
      case DartPackage.NAMED_PARAMETER_TYPE__TYPE:
        return type != null;
      case DartPackage.NAMED_PARAMETER_TYPE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (isRequired: ");
    result.append(isRequired);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //NamedParameterTypeImpl
