/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart.impl;

import it.lorenzodeluca.dart.dart.DartPackage;
import it.lorenzodeluca.dart.dart.OptionalOrNamedFormalParameters;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Optional Or Named Formal Parameters</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OptionalOrNamedFormalParametersImpl extends MinimalEObjectImpl.Container implements OptionalOrNamedFormalParameters
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OptionalOrNamedFormalParametersImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DartPackage.Literals.OPTIONAL_OR_NAMED_FORMAL_PARAMETERS;
  }

} //OptionalOrNamedFormalParametersImpl
