/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart.impl;

import it.lorenzodeluca.dart.dart.DartPackage;
import it.lorenzodeluca.dart.dart.ThrowExpressionWithoutCascade;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Throw Expression Without Cascade</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ThrowExpressionWithoutCascadeImpl extends ExpressionImpl implements ThrowExpressionWithoutCascade
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ThrowExpressionWithoutCascadeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DartPackage.eINSTANCE.getThrowExpressionWithoutCascade();
  }

} //ThrowExpressionWithoutCascadeImpl
