/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart.impl;

import it.lorenzodeluca.dart.dart.DartPackage;
import it.lorenzodeluca.dart.dart.TypeArguments;
import it.lorenzodeluca.dart.dart.TypeName;
import it.lorenzodeluca.dart.dart.TypeNotFunction;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Type Not Function</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.TypeNotFunctionImpl#isIsVoid <em>Is Void</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.TypeNotFunctionImpl#isIsNullable <em>Is Nullable</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.TypeNotFunctionImpl#getName <em>Name</em>}</li>
 *   <li>{@link it.lorenzodeluca.dart.dart.impl.TypeNotFunctionImpl#getTypeArguments <em>Type Arguments</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TypeNotFunctionImpl extends TypeImpl implements TypeNotFunction
{
  /**
   * The default value of the '{@link #isIsVoid() <em>Is Void</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsVoid()
   * @generated
   * @ordered
   */
  protected static final boolean IS_VOID_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsVoid() <em>Is Void</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsVoid()
   * @generated
   * @ordered
   */
  protected boolean isVoid = IS_VOID_EDEFAULT;

  /**
   * The default value of the '{@link #isIsNullable() <em>Is Nullable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsNullable()
   * @generated
   * @ordered
   */
  protected static final boolean IS_NULLABLE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsNullable() <em>Is Nullable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsNullable()
   * @generated
   * @ordered
   */
  protected boolean isNullable = IS_NULLABLE_EDEFAULT;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected TypeName name;

  /**
   * The cached value of the '{@link #getTypeArguments() <em>Type Arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeArguments()
   * @generated
   * @ordered
   */
  protected TypeArguments typeArguments;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TypeNotFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DartPackage.eINSTANCE.getTypeNotFunction();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsVoid()
  {
    return isVoid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsVoid(boolean newIsVoid)
  {
    boolean oldIsVoid = isVoid;
    isVoid = newIsVoid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.TYPE_NOT_FUNCTION__IS_VOID, oldIsVoid, isVoid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsNullable()
  {
    return isNullable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsNullable(boolean newIsNullable)
  {
    boolean oldIsNullable = isNullable;
    isNullable = newIsNullable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.TYPE_NOT_FUNCTION__IS_NULLABLE, oldIsNullable, isNullable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypeName getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetName(TypeName newName, NotificationChain msgs)
  {
    TypeName oldName = name;
    name = newName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DartPackage.TYPE_NOT_FUNCTION__NAME, oldName, newName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(TypeName newName)
  {
    if (newName != name)
    {
      NotificationChain msgs = null;
      if (name != null)
        msgs = ((InternalEObject)name).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DartPackage.TYPE_NOT_FUNCTION__NAME, null, msgs);
      if (newName != null)
        msgs = ((InternalEObject)newName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DartPackage.TYPE_NOT_FUNCTION__NAME, null, msgs);
      msgs = basicSetName(newName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.TYPE_NOT_FUNCTION__NAME, newName, newName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypeArguments getTypeArguments()
  {
    return typeArguments;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeArguments(TypeArguments newTypeArguments, NotificationChain msgs)
  {
    TypeArguments oldTypeArguments = typeArguments;
    typeArguments = newTypeArguments;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DartPackage.TYPE_NOT_FUNCTION__TYPE_ARGUMENTS, oldTypeArguments, newTypeArguments);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTypeArguments(TypeArguments newTypeArguments)
  {
    if (newTypeArguments != typeArguments)
    {
      NotificationChain msgs = null;
      if (typeArguments != null)
        msgs = ((InternalEObject)typeArguments).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DartPackage.TYPE_NOT_FUNCTION__TYPE_ARGUMENTS, null, msgs);
      if (newTypeArguments != null)
        msgs = ((InternalEObject)newTypeArguments).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DartPackage.TYPE_NOT_FUNCTION__TYPE_ARGUMENTS, null, msgs);
      msgs = basicSetTypeArguments(newTypeArguments, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DartPackage.TYPE_NOT_FUNCTION__TYPE_ARGUMENTS, newTypeArguments, newTypeArguments));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DartPackage.TYPE_NOT_FUNCTION__NAME:
        return basicSetName(null, msgs);
      case DartPackage.TYPE_NOT_FUNCTION__TYPE_ARGUMENTS:
        return basicSetTypeArguments(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DartPackage.TYPE_NOT_FUNCTION__IS_VOID:
        return isIsVoid();
      case DartPackage.TYPE_NOT_FUNCTION__IS_NULLABLE:
        return isIsNullable();
      case DartPackage.TYPE_NOT_FUNCTION__NAME:
        return getName();
      case DartPackage.TYPE_NOT_FUNCTION__TYPE_ARGUMENTS:
        return getTypeArguments();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DartPackage.TYPE_NOT_FUNCTION__IS_VOID:
        setIsVoid((Boolean)newValue);
        return;
      case DartPackage.TYPE_NOT_FUNCTION__IS_NULLABLE:
        setIsNullable((Boolean)newValue);
        return;
      case DartPackage.TYPE_NOT_FUNCTION__NAME:
        setName((TypeName)newValue);
        return;
      case DartPackage.TYPE_NOT_FUNCTION__TYPE_ARGUMENTS:
        setTypeArguments((TypeArguments)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.TYPE_NOT_FUNCTION__IS_VOID:
        setIsVoid(IS_VOID_EDEFAULT);
        return;
      case DartPackage.TYPE_NOT_FUNCTION__IS_NULLABLE:
        setIsNullable(IS_NULLABLE_EDEFAULT);
        return;
      case DartPackage.TYPE_NOT_FUNCTION__NAME:
        setName((TypeName)null);
        return;
      case DartPackage.TYPE_NOT_FUNCTION__TYPE_ARGUMENTS:
        setTypeArguments((TypeArguments)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DartPackage.TYPE_NOT_FUNCTION__IS_VOID:
        return isVoid != IS_VOID_EDEFAULT;
      case DartPackage.TYPE_NOT_FUNCTION__IS_NULLABLE:
        return isNullable != IS_NULLABLE_EDEFAULT;
      case DartPackage.TYPE_NOT_FUNCTION__NAME:
        return name != null;
      case DartPackage.TYPE_NOT_FUNCTION__TYPE_ARGUMENTS:
        return typeArguments != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (isVoid: ");
    result.append(isVoid);
    result.append(", isNullable: ");
    result.append(isNullable);
    result.append(')');
    return result.toString();
  }

} //TypeNotFunctionImpl
