/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.tests;

import com.google.inject.Inject;
import it.lorenzodeluca.dart.dart.CompilationUnit;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(DartInjectorProvider.class)
@SuppressWarnings("all")
public class DartParsingTest {
  @Inject
  private ParseHelper<CompilationUnit> parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nAccess restriction: The type Assertions is not accessible due to restriction on required project it.lorenzodeluca.dart.tests"
      + "\nAccess restriction: The type Assertions is not accessible due to restriction on required project it.lorenzodeluca.dart.tests");
  }
}
