/*
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.serializer;

import com.google.inject.Inject;
import it.lorenzodeluca.dart.dart.ClassDeclaration;
import it.lorenzodeluca.dart.dart.CompilationUnit;
import it.lorenzodeluca.dart.dart.DartPackage;
import it.lorenzodeluca.dart.dart.EnumDeclaration;
import it.lorenzodeluca.dart.dart.ExtensionDeclaration;
import it.lorenzodeluca.dart.dart.FunctionDeclaration;
import it.lorenzodeluca.dart.dart.LibraryExport;
import it.lorenzodeluca.dart.dart.LibraryImport;
import it.lorenzodeluca.dart.dart.LibraryName;
import it.lorenzodeluca.dart.dart.MixinDeclaration;
import it.lorenzodeluca.dart.dart.PartDirective;
import it.lorenzodeluca.dart.dart.ScriptTag;
import it.lorenzodeluca.dart.dart.TypeAlias;
import it.lorenzodeluca.dart.dart.TypeArguments;
import it.lorenzodeluca.dart.dart.TypeName;
import it.lorenzodeluca.dart.dart.VariableDeclaration;
import it.lorenzodeluca.dart.dart.VariableSingleDeclaration;
import it.lorenzodeluca.dart.services.DartGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class DartSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DartGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == DartPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DartPackage.CLASS_DECLARATION:
				sequence_ClassDeclaration(context, (ClassDeclaration) semanticObject); 
				return; 
			case DartPackage.COMPILATION_UNIT:
				sequence_CompilationUnit(context, (CompilationUnit) semanticObject); 
				return; 
			case DartPackage.ENUM_DECLARATION:
				sequence_EnumDeclaration(context, (EnumDeclaration) semanticObject); 
				return; 
			case DartPackage.EXTENSION_DECLARATION:
				sequence_ExtensionDeclaration(context, (ExtensionDeclaration) semanticObject); 
				return; 
			case DartPackage.FUNCTION_DECLARATION:
				sequence_FunctionDeclaration(context, (FunctionDeclaration) semanticObject); 
				return; 
			case DartPackage.LIBRARY_EXPORT:
				sequence_LibraryExport(context, (LibraryExport) semanticObject); 
				return; 
			case DartPackage.LIBRARY_IMPORT:
				sequence_LibraryImport(context, (LibraryImport) semanticObject); 
				return; 
			case DartPackage.LIBRARY_NAME:
				sequence_LibraryName(context, (LibraryName) semanticObject); 
				return; 
			case DartPackage.MIXIN_DECLARATION:
				sequence_MixinDeclaration(context, (MixinDeclaration) semanticObject); 
				return; 
			case DartPackage.PART_DIRECTIVE:
				sequence_PartDirective(context, (PartDirective) semanticObject); 
				return; 
			case DartPackage.SCRIPT_TAG:
				sequence_ScriptTag(context, (ScriptTag) semanticObject); 
				return; 
			case DartPackage.TYPE_ALIAS:
				sequence_TypeAlias(context, (TypeAlias) semanticObject); 
				return; 
			case DartPackage.TYPE_ARGUMENTS:
				sequence_TypeArguments(context, (TypeArguments) semanticObject); 
				return; 
			case DartPackage.TYPE_NAME:
				if (rule == grammarAccess.getTypeNameRule()) {
					sequence_TypeName(context, (TypeName) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getTypeRule()) {
					sequence_Type_TypeName(context, (TypeName) semanticObject); 
					return; 
				}
				else break;
			case DartPackage.VARIABLE_DECLARATION:
				sequence_VariableDeclaration(context, (VariableDeclaration) semanticObject); 
				return; 
			case DartPackage.VARIABLE_SINGLE_DECLARATION:
				sequence_VariableSingleDeclaration(context, (VariableSingleDeclaration) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelDeclaration returns ClassDeclaration
	 *     ClassDeclaration returns ClassDeclaration
	 *
	 * Constraint:
	 *     (metadata+=Metadata* name=ID)
	 * </pre>
	 */
	protected void sequence_ClassDeclaration(ISerializationContext context, ClassDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     CompilationUnit returns CompilationUnit
	 *
	 * Constraint:
	 *     (
	 *         (scriptTag=ScriptTag ((directives+=ImportOrExport+ declarations+=TopLevelDeclaration+) | declarations+=TopLevelDeclaration+)) | 
	 *         (
	 *             ((scriptTag=ScriptTag libraryName=LibraryName) | libraryName=LibraryName) 
	 *             ((directives+=ImportOrExport+ declarations+=TopLevelDeclaration+) | declarations+=TopLevelDeclaration+)
	 *         ) | 
	 *         (
	 *             (
	 *                 (scriptTag=ScriptTag ((libraryName=LibraryName directives+=ImportOrExport+) | directives+=ImportOrExport+)) | 
	 *                 (libraryName=LibraryName directives+=ImportOrExport+) | 
	 *                 directives+=ImportOrExport+
	 *             )? 
	 *             partDirectives+=PartDirective+ 
	 *             declarations+=TopLevelDeclaration+
	 *         ) | 
	 *         (directives+=ImportOrExport+ declarations+=TopLevelDeclaration+) | 
	 *         declarations+=TopLevelDeclaration+
	 *     )?
	 * </pre>
	 */
	protected void sequence_CompilationUnit(ISerializationContext context, CompilationUnit semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelDeclaration returns EnumDeclaration
	 *     EnumDeclaration returns EnumDeclaration
	 *
	 * Constraint:
	 *     (metadata+=Metadata* name=ID)
	 * </pre>
	 */
	protected void sequence_EnumDeclaration(ISerializationContext context, EnumDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelDeclaration returns ExtensionDeclaration
	 *     ExtensionDeclaration returns ExtensionDeclaration
	 *
	 * Constraint:
	 *     (metadata+=Metadata* name=ID)
	 * </pre>
	 */
	protected void sequence_ExtensionDeclaration(ISerializationContext context, ExtensionDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelDeclaration returns FunctionDeclaration
	 *     FunctionDeclaration returns FunctionDeclaration
	 *
	 * Constraint:
	 *     (metadata+=Metadata* external?='external'? returnType=ID? name=ID body=FunctionBody?)
	 * </pre>
	 */
	protected void sequence_FunctionDeclaration(ISerializationContext context, FunctionDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ImportOrExport returns LibraryExport
	 *     LibraryExport returns LibraryExport
	 *
	 * Constraint:
	 *     exportURI=STRING
	 * </pre>
	 */
	protected void sequence_LibraryExport(ISerializationContext context, LibraryExport semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DartPackage.Literals.LIBRARY_EXPORT__EXPORT_URI) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DartPackage.Literals.LIBRARY_EXPORT__EXPORT_URI));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLibraryExportAccess().getExportURISTRINGTerminalRuleCall_1_0(), semanticObject.getExportURI());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ImportOrExport returns LibraryImport
	 *     LibraryImport returns LibraryImport
	 *
	 * Constraint:
	 *     (importURI=STRING alias=ID?)
	 * </pre>
	 */
	protected void sequence_LibraryImport(ISerializationContext context, LibraryImport semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LibraryName returns LibraryName
	 *
	 * Constraint:
	 *     name=DottedIdentifier
	 * </pre>
	 */
	protected void sequence_LibraryName(ISerializationContext context, LibraryName semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DartPackage.Literals.LIBRARY_NAME__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DartPackage.Literals.LIBRARY_NAME__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLibraryNameAccess().getNameDottedIdentifierParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelDeclaration returns MixinDeclaration
	 *     MixinDeclaration returns MixinDeclaration
	 *
	 * Constraint:
	 *     (metadata+=Metadata* name=ID)
	 * </pre>
	 */
	protected void sequence_MixinDeclaration(ISerializationContext context, MixinDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PartDirective returns PartDirective
	 *
	 * Constraint:
	 *     partURI=STRING
	 * </pre>
	 */
	protected void sequence_PartDirective(ISerializationContext context, PartDirective semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DartPackage.Literals.PART_DIRECTIVE__PART_URI) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DartPackage.Literals.PART_DIRECTIVE__PART_URI));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPartDirectiveAccess().getPartURISTRINGTerminalRuleCall_1_0(), semanticObject.getPartURI());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ScriptTag returns ScriptTag
	 *
	 * Constraint:
	 *     content=SCRIPT_TAG
	 * </pre>
	 */
	protected void sequence_ScriptTag(ISerializationContext context, ScriptTag semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DartPackage.Literals.SCRIPT_TAG__CONTENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DartPackage.Literals.SCRIPT_TAG__CONTENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getScriptTagAccess().getContentSCRIPT_TAGTerminalRuleCall_0(), semanticObject.getContent());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelDeclaration returns TypeAlias
	 *     TypeAlias returns TypeAlias
	 *
	 * Constraint:
	 *     (metadata+=Metadata* name=ID)
	 * </pre>
	 */
	protected void sequence_TypeAlias(ISerializationContext context, TypeAlias semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeArguments returns TypeArguments
	 *
	 * Constraint:
	 *     (elements+=Type elements+=Type*)
	 * </pre>
	 */
	protected void sequence_TypeArguments(ISerializationContext context, TypeArguments semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeName returns TypeName
	 *
	 * Constraint:
	 *     (name=ID typeArguments=TypeArguments?)
	 * </pre>
	 */
	protected void sequence_TypeName(ISerializationContext context, TypeName semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Type returns TypeName
	 *
	 * Constraint:
	 *     (name=ID typeArguments=TypeArguments? nullable?='?'?)
	 * </pre>
	 */
	protected void sequence_Type_TypeName(ISerializationContext context, TypeName semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelDeclaration returns VariableDeclaration
	 *     VariableDeclaration returns VariableDeclaration
	 *
	 * Constraint:
	 *     (
	 *         metadata+=Metadata* 
	 *         late?='late'? 
	 *         ((modifier=VariableModifier type=Type?) | type=Type) 
	 *         variables+=VariableSingleDeclaration 
	 *         variables+=VariableSingleDeclaration*
	 *     )
	 * </pre>
	 */
	protected void sequence_VariableDeclaration(ISerializationContext context, VariableDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     VariableSingleDeclaration returns VariableSingleDeclaration
	 *
	 * Constraint:
	 *     (name=ID initialValue=Expression?)
	 * </pre>
	 */
	protected void sequence_VariableSingleDeclaration(ISerializationContext context, VariableSingleDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
