/**
 * generated by Xtext 2.41.0
 */
package it.lorenzodeluca.dart.dart.util;

import it.lorenzodeluca.dart.dart.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see it.lorenzodeluca.dart.dart.DartPackage
 * @generated
 */
public class DartAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static DartPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DartAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = DartPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DartSwitch<Adapter> modelSwitch =
    new DartSwitch<Adapter>()
    {
      @Override
      public Adapter caseCompilationUnit(CompilationUnit object)
      {
        return createCompilationUnitAdapter();
      }
      @Override
      public Adapter caseScriptTag(ScriptTag object)
      {
        return createScriptTagAdapter();
      }
      @Override
      public Adapter caseLibraryName(LibraryName object)
      {
        return createLibraryNameAdapter();
      }
      @Override
      public Adapter caseImportOrExport(ImportOrExport object)
      {
        return createImportOrExportAdapter();
      }
      @Override
      public Adapter caseLibraryImport(LibraryImport object)
      {
        return createLibraryImportAdapter();
      }
      @Override
      public Adapter caseLibraryExport(LibraryExport object)
      {
        return createLibraryExportAdapter();
      }
      @Override
      public Adapter casePartDirective(PartDirective object)
      {
        return createPartDirectiveAdapter();
      }
      @Override
      public Adapter caseTopLevelDeclaration(TopLevelDeclaration object)
      {
        return createTopLevelDeclarationAdapter();
      }
      @Override
      public Adapter caseClassDeclaration(ClassDeclaration object)
      {
        return createClassDeclarationAdapter();
      }
      @Override
      public Adapter caseMixinDeclaration(MixinDeclaration object)
      {
        return createMixinDeclarationAdapter();
      }
      @Override
      public Adapter caseExtensionDeclaration(ExtensionDeclaration object)
      {
        return createExtensionDeclarationAdapter();
      }
      @Override
      public Adapter caseEnumDeclaration(EnumDeclaration object)
      {
        return createEnumDeclarationAdapter();
      }
      @Override
      public Adapter caseTypeAlias(TypeAlias object)
      {
        return createTypeAliasAdapter();
      }
      @Override
      public Adapter caseFunctionDeclaration(FunctionDeclaration object)
      {
        return createFunctionDeclarationAdapter();
      }
      @Override
      public Adapter caseVariableDeclaration(VariableDeclaration object)
      {
        return createVariableDeclarationAdapter();
      }
      @Override
      public Adapter caseVariableSingleDeclaration(VariableSingleDeclaration object)
      {
        return createVariableSingleDeclarationAdapter();
      }
      @Override
      public Adapter caseType(Type object)
      {
        return createTypeAdapter();
      }
      @Override
      public Adapter caseTypeName(TypeName object)
      {
        return createTypeNameAdapter();
      }
      @Override
      public Adapter caseTypeArguments(TypeArguments object)
      {
        return createTypeArgumentsAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.CompilationUnit <em>Compilation Unit</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.CompilationUnit
   * @generated
   */
  public Adapter createCompilationUnitAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.ScriptTag <em>Script Tag</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.ScriptTag
   * @generated
   */
  public Adapter createScriptTagAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.LibraryName <em>Library Name</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.LibraryName
   * @generated
   */
  public Adapter createLibraryNameAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.ImportOrExport <em>Import Or Export</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.ImportOrExport
   * @generated
   */
  public Adapter createImportOrExportAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.LibraryImport <em>Library Import</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.LibraryImport
   * @generated
   */
  public Adapter createLibraryImportAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.LibraryExport <em>Library Export</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.LibraryExport
   * @generated
   */
  public Adapter createLibraryExportAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.PartDirective <em>Part Directive</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.PartDirective
   * @generated
   */
  public Adapter createPartDirectiveAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.TopLevelDeclaration <em>Top Level Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.TopLevelDeclaration
   * @generated
   */
  public Adapter createTopLevelDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.ClassDeclaration <em>Class Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.ClassDeclaration
   * @generated
   */
  public Adapter createClassDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.MixinDeclaration <em>Mixin Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.MixinDeclaration
   * @generated
   */
  public Adapter createMixinDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.ExtensionDeclaration <em>Extension Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.ExtensionDeclaration
   * @generated
   */
  public Adapter createExtensionDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.EnumDeclaration <em>Enum Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.EnumDeclaration
   * @generated
   */
  public Adapter createEnumDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.TypeAlias <em>Type Alias</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.TypeAlias
   * @generated
   */
  public Adapter createTypeAliasAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.FunctionDeclaration <em>Function Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.FunctionDeclaration
   * @generated
   */
  public Adapter createFunctionDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.VariableDeclaration
   * @generated
   */
  public Adapter createVariableDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.VariableSingleDeclaration <em>Variable Single Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.VariableSingleDeclaration
   * @generated
   */
  public Adapter createVariableSingleDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.Type
   * @generated
   */
  public Adapter createTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.TypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.TypeName
   * @generated
   */
  public Adapter createTypeNameAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link it.lorenzodeluca.dart.dart.TypeArguments <em>Type Arguments</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see it.lorenzodeluca.dart.dart.TypeArguments
   * @generated
   */
  public Adapter createTypeArgumentsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //DartAdapterFactory
